<?php

declare(strict_types=1);

namespace App\Domain\Docs;

use App\Domain\Access\ScreenKey;
use App\Domain\Access\Screens;
use App\Filament\Modul;
use App\Filament\Pages\Reports\ReportPage;
use App\Filament\Pages\Reports\ReportRegistry;
use App\Filament\Support\ErpPage;
use App\Filament\Support\ErpResource;
use App\Filament\Support\PlaceholderPage;
use App\Modules\ModuleRegistry;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Facades\Filament;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Fieldset;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Str;
use ReflectionClass;
use Throwable;

/**
 * Writes docs/standard from the code: one page per module group, one section
 * per screen, with the list's columns, filters and actions, the form's fields
 * (label, column, type, required), tabs, sections and line grids, read from
 * the Filament resources and pages themselves. The hand-kept notes in
 * docs/standard/_notes (behaviours, rules, open questions) are prepended.
 * The pages are therefore always what the code does; `php artisan
 * erp:standard` regenerates them and StandardDocsTest fails when they are stale.
 */
final class StandardWriter
{
    public function __construct(private readonly string $notesDir, private readonly ModuleRegistry $modules) {}

    /** @return array<string, string> file name → markdown */
    public function pages(): array
    {
        $panel = Filament::getPanel('admin');
        $screens = [];
        foreach ($panel->getResources() as $resource) {
            if (is_subclass_of($resource, ErpResource::class)) {
                $screens[$resource::menuKey()->value] = ['resource' => $resource];
            }
        }
        foreach ($panel->getPages() as $page) {
            if (is_subclass_of($page, ErpPage::class) && ! is_subclass_of($page, ReportPage::class)) {
                $screens[$page::menuKey()->value] = ['page' => $page];
            }
        }

        $out = ['README.md' => $this->index($screens)];
        foreach (Modul::cases() as $modul) {
            $out[$modul->value.'.md'] = $this->modulePage($modul, $screens);
        }

        return $out;
    }

    /** @param  array<string, array{resource?: class-string, page?: class-string}>  $screens */
    private function index(array $screens): string
    {
        $md = "# The standard\n\n";
        $md .= $this->notes('README');
        $md .= "## Modules\n\n| Module group | Switchable modules in it | Screens | Page |\n|---|---|---|---|\n";
        foreach (Modul::cases() as $modul) {
            $keys = $this->keysOf($modul);
            $owners = [];
            foreach ($keys as $key) {
                $owner = $this->modules->ownerOf($key);
                if ($owner === null) {
                    continue;
                }
                $feature = $owner::featureForKey($key);
                $owners[$owner::key()] = $feature === null ? "`{$owner::key()}` (always on)" : "`{$owner::key()}` (Preferences → Features → {$feature->label()})";
            }
            $built = count(array_filter($keys, fn (ScreenKey $k) => isset($screens[$k->value])));
            $md .= sprintf("| %s | %s | %d | [%s.md](%s.md) |\n", $modul->getLabel(), implode('<br>', $owners) ?: '—', $built, $modul->value, $modul->value);
        }
        $md .= "\n## How to read a page\n\n";
        $md .= "Each screen lists what its list shows (columns, filters, actions) and what its form holds: every field with its label, the column it is stored in, its type and whether it is required; tabs, sections and line grids as the form groups them. A line grid is a table of lines inside the document, named by its columns. The reports page lists every report of the catalogue with its filters.\n\n";
        $md .= "Generated by `php artisan erp:standard` from the Filament resources and pages; edit the code, then regenerate. The notes above each module come from `docs/standard/_notes/<module>.md` and are written by hand.\n";

        return $md;
    }

    /** @param  array<string, array{resource?: class-string, page?: class-string}>  $screens */
    private function modulePage(Modul $modul, array $screens): string
    {
        $keys = $this->keysOf($modul);
        $md = "# {$modul->getLabel()}\n\n";
        $md .= "Module group `{$modul->value}`. ".count($keys)." screens in the standard menu.\n\n";
        $md .= $this->notes($modul->value);
        $md .= "## Screens\n\n";
        foreach ($keys as $key) {
            $md .= '- ['.$key->label().'](#'.Str::slug($key->label()).')'.(isset($screens[$key->value]) ? '' : ' (not reproduced)')."\n";
        }
        $md .= "\n";
        foreach ($keys as $key) {
            $md .= $this->screen($key, $screens[$key->value] ?? null);
        }
        if ($modul === Modul::Reports) {
            $md .= $this->reports();
        }

        return $md;
    }

    /** @return list<ScreenKey> */
    private function keysOf(Modul $modul): array
    {
        return Screens::of($modul);
    }

    /** @param  array{resource?: class-string, page?: class-string}|null  $screen */
    private function screen(ScreenKey $key, ?array $screen): string
    {
        $md = "## {$key->label()}\n\n";
        $owner = $this->modules->ownerOf($key);
        $feature = $owner === null ? null : $owner::featureForKey($key);
        $md .= "Menu key `{$key->value}`";
        if ($owner !== null) {
            $md .= " · module `{$owner::key()}`".($feature ? " · switched by Preferences → Features → {$feature->label()}" : '');
        }
        $md .= "\n\n";

        if ($screen === null) {
            $md .= "Not reproduced: a vendor service of the original product.\n\n";

            return $md;
        }

        try {
            if (isset($screen['resource'])) {
                $md .= $this->resource($screen['resource']);
            } else {
                $md .= $this->page($screen['page']);
            }
        } catch (Throwable $e) {
            $md .= '_Could not be introspected: '.class_basename($e).' — '.$this->text($e->getMessage())."_\n\n";
        }

        return $md;
    }

    /** @param  class-string<ErpResource>  $resource */
    private function resource(string $resource): string
    {
        $md = '';
        $pages = $resource::getPages();
        if (isset($pages['index'])) {
            $list = new ($pages['index']->getPage());
            $md .= $this->table($resource::table(Table::make($list)));
        }
        // A page stands in for Livewire: some components ask the schema for it while they are built.
        $host = isset($pages['create']) ? new ($pages['create']->getPage()) : (isset($pages['index']) ? new ($pages['index']->getPage()) : null);
        $schema = $resource::form($host ? Schema::make($host) : Schema::make());
        $md .= $this->form($schema->getComponents());

        return $md;
    }

    /** @param  class-string<ErpPage>  $pageClass */
    private function page(string $pageClass): string
    {
        $page = new $pageClass;
        if ($page instanceof PlaceholderPage) {
            $method = (new ReflectionClass($page))->getMethod('explanation');

            return 'Planned for a later release. '.$this->text((string) $method->invoke($page))."\n\n";
        }
        $md = '';
        if (method_exists($page, 'form')) {
            $md .= $this->form($page->form(Schema::make($page))->getComponents(), 'Filters and inputs');
        }
        if (method_exists($page, 'table')) {
            $md .= $this->table($page->table(Table::make($page)));
        }
        if ($md === '') {
            $md = "A read-only screen with its own layout.\n\n";
        }

        return $md;
    }

    private function table(Table $table): string
    {
        $columns = array_map(fn ($c) => $this->label($c), $table->getColumns());
        $filters = array_map(fn ($f) => $this->label($f), $table->getFilters());
        $actions = [];
        foreach ([...$table->getHeaderActions(), ...$table->getRecordActions(), ...$table->getToolbarActions()] as $action) {
            foreach ($action instanceof ActionGroup ? $action->getActions() : [$action] as $a) {
                $label = $this->label($a);
                if ($label !== '' && ! in_array($label, $actions, true)) {
                    $actions[] = $label;
                }
            }
        }
        $md = "### List\n\n";
        $md .= '**Columns:** '.($this->join($columns) ?: '—')."\n\n";
        if ($filters !== []) {
            $md .= '**Filters:** '.$this->join($filters)."\n\n";
        }
        if ($actions !== []) {
            $md .= '**Actions:** '.$this->join($actions)."\n\n";
        }

        return $md;
    }

    /** @param  array<int, mixed>  $components */
    private function form(array $components, string $heading = 'Form'): string
    {
        $lines = [];
        $rows = [];
        $actions = [];
        $this->walk($components, $lines, $rows, $actions, 0);
        $this->flush($lines, $rows);
        if ($lines === [] && $actions === []) {
            return '';
        }
        $md = "### {$heading}\n\n".implode('', $lines);
        if ($actions !== []) {
            $md .= '**Actions:** '.$this->join($actions)."\n\n";
        }

        return $md;
    }

    /**
     * @param  array<int, mixed>  $components
     * @param  list<string>  $lines
     * @param  list<string>  $rows
     * @param  list<string>  $actions
     */
    private function walk(array $components, array &$lines, array &$rows, array &$actions, int $depth): void
    {
        foreach ($components as $c) {
            if ($c instanceof Hidden) {
                continue;
            }
            if ($c instanceof Action) {
                $label = $this->label($c);
                if ($label !== '' && ! in_array($label, $actions, true)) {
                    $actions[] = $label;
                }

                continue;
            }
            if ($c instanceof Repeater) {
                $this->flush($lines, $rows);
                $columns = [];
                foreach ($c->getTableColumns() ?? [] as $col) {
                    $columns[] = $this->label($col);
                }
                if ($columns === []) {
                    foreach ($this->children($c) as $child) {
                        if (! $child instanceof Hidden) {
                            $columns[] = $this->label($child);
                        }
                    }
                }
                $lines[] = '**Line grid "'.$this->label($c).'":** '.($this->join(array_filter($columns)) ?: '—')."\n\n";

                continue;
            }
            if ($c instanceof Tab) {
                $this->flush($lines, $rows);
                $lines[] = '#### Tab: '.$this->label($c)."\n\n";
                $this->walk($this->children($c), $lines, $rows, $actions, $depth + 1);
                $this->flush($lines, $rows);

                continue;
            }
            if ($c instanceof Section || $c instanceof Fieldset) {
                $label = $c instanceof Section ? $this->text($c->getHeading()) : $this->label($c);
                $this->flush($lines, $rows);
                if ($label !== '') {
                    $lines[] = '**'.($c instanceof Section ? 'Section' : 'Fieldset').": {$label}**\n\n";
                }
                $this->walk($this->children($c), $lines, $rows, $actions, $depth + 1);
                $this->flush($lines, $rows);

                continue;
            }
            $children = $this->children($c);
            if ($children !== [] && ! method_exists($c, 'getName')) {
                $this->walk($children, $lines, $rows, $actions, $depth + 1); // Grid, Group, Tabs, Split: transparent

                continue;
            }
            if ($children !== [] && $c->getName() === null) {
                $this->walk($children, $lines, $rows, $actions, $depth + 1);

                continue;
            }
            $rows[] = sprintf('| %s | `%s` | %s | %s |', $this->label($c) ?: '—', (string) $c->getName(), $this->type($c), $this->required($c) ? 'yes' : '');
        }
    }

    /**
     * @param  list<string>  $lines
     * @param  list<string>  $rows
     */
    private function flush(array &$lines, array &$rows): void
    {
        if ($rows === []) {
            return;
        }
        $lines[] = "| Field | Column | Type | Required |\n|---|---|---|---|\n".implode("\n", $rows)."\n\n";
        $rows = [];
    }

    /** @return array<int, mixed> */
    private function children(mixed $component): array
    {
        try {
            if (method_exists($component, 'getDefaultChildComponents')) {
                return $component->getDefaultChildComponents();
            }
            if (method_exists($component, 'getChildComponents')) {
                return $component->getChildComponents();
            }
        } catch (Throwable) {
        }

        return [];
    }

    private function type(mixed $c): string
    {
        $base = class_basename($c);
        if ($c instanceof TextInput) {
            // A masked amount (MoneyInput) is a number even when it takes decimals in the convention's separator.
            return rescue(fn () => $c->isNumeric() || (fn () => $this->mask !== null)->call($c), false, false) ? 'number' : 'text';
        }

        return match ($base) {
            'Textarea' => 'textarea',
            'Select' => rescue(fn () => $c->isMultiple(), false, false) ? 'multi-select' : 'select',
            'DatePicker' => 'date',
            'DateTimePicker' => 'date and time',
            'TimePicker' => 'time',
            'Toggle', 'Checkbox' => 'toggle',
            'Radio' => 'radio',
            'CheckboxList' => 'checkbox list',
            'FileUpload' => 'file',
            'RichEditor', 'MarkdownEditor' => 'rich text',
            'Placeholder', 'Text' => 'computed',
            'ColorPicker' => 'colour',
            'KeyValue' => 'key / value',
            'TagsInput' => 'tags',
            default => Str::lower(Str::headline($base)),
        };
    }

    private function required(mixed $c): bool
    {
        return method_exists($c, 'isRequired') ? (bool) rescue(fn () => $c->isRequired(), false, false) : false;
    }

    private function label(mixed $c): string
    {
        if (! method_exists($c, 'getLabel')) {
            return '';
        }

        return $this->text(rescue(fn () => $c->getLabel(), '', false));
    }

    private function text(mixed $value): string
    {
        if ($value instanceof Htmlable) {
            $value = strip_tags($value->toHtml());
        }

        return str_replace(['|', "\n"], ['\\|', ' '], trim((string) $value));
    }

    /** @param  array<int, string>  $items */
    private function join(array $items): string
    {
        return implode(' · ', array_values(array_filter($items, fn (string $i) => $i !== '')));
    }

    private function reports(): string
    {
        $md = "## Reports in the catalogue\n\n";
        $md .= "Every figure is computed from the journal and the stock ledger when the report opens; nothing is stored. Each report exports to Excel.\n\n";
        $md .= "| Report | Group | Needs | Filters | What it shows |\n|---|---|---|---|---|\n";
        foreach (ReportRegistry::every() as $class) {
            $page = new $class;
            $filters = [];
            try {
                $filters = $this->leafLabels($page->form(Schema::make($page))->getComponents());
            } catch (Throwable) {
            }
            $md .= sprintf("| %s | %s | %s | %s | %s |\n", $class::title(), $class::group(), $class::requires() ? "`{$class::requires()}`" : 'always on', $this->join($filters) ?: '—', $this->text($class::description()));
        }

        return $md."\n";
    }

    /**
     * The labels of the fields a schema holds, through its containers.
     *
     * @param  array<int, mixed>  $components
     * @return list<string>
     */
    private function leafLabels(array $components): array
    {
        $labels = [];
        foreach ($components as $c) {
            if ($c instanceof Hidden || $c instanceof Action) {
                continue;
            }
            $children = $this->children($c);
            if ($children !== [] && ! $c instanceof Repeater) {
                array_push($labels, ...$this->leafLabels($children));

                continue;
            }
            $label = $this->label($c);
            if ($label !== '') {
                $labels[] = $label;
            }
        }

        return $labels;
    }

    private function notes(string $name): string
    {
        $file = rtrim($this->notesDir, '/')."/{$name}.md";

        return is_file($file) ? rtrim(file_get_contents($file))."\n\n" : '';
    }
}
